
dirname <- "/home/rapela/dev/research/programs/src/R/contributed"
source(sprintf("%s/Rallfun-v34.txt", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/math"
source(sprintf("%s/computeSignedAngleBtwTwoVectors.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/timeFreq"
source(sprintf("%s/binTrialsAmplitudesByPhaseFromTimeFreqs.R", dirname))
source(sprintf("%s/computeERSPFromTimeFreqsMaskedWithBootstrapSignificance.R", dirname))
source(sprintf("%s/computeITCFromTimeFreqsMaskedWithRayleighSignificance.R", dirname))
source(sprintf("%s/plotMorletWaveletInfo.R", dirname))
source(sprintf("%s/getMorletWaveletInfo.R", dirname))
source(sprintf("%s/getScales.R", dirname))
source(sprintf("%s/getFreqs.R", dirname))
source(sprintf("%s/performMorletWTSingleTrial.R", dirname))
# source(sprintf("%s/performMorletWTSingleTrials.R", dirname))
source(sprintf("%s/computeITCFromTimeFreqs.R", dirname))
source(sprintf("%s/computeTimeFreqRayleighPValues.R", dirname))
source(sprintf("%s/computeITCWithSignificanceMaskAndPeakCI.R", dirname))
source(sprintf("%s/computeITCFromPhaseERPImage.R", dirname))
source(sprintf("%s/getPeakTimeFreq.R", dirname))
source(sprintf("%s/bootstrapITCFromPhases.R", dirname))
source(sprintf("%s/computeITCBootstrapCIs.R", dirname))
source(sprintf("%s/computeITCFromPhases.R", dirname))
source(sprintf("%s/computePLIFromPhases.R", dirname))
source(sprintf("%s/prepareDataAndComputeAmplitudeAndPhaseERPImages.R", dirname))
source(sprintf("%s/computeAmplitudeAndPhaseERPImagesCGT.R", dirname))
source(sprintf("%s/computeITCFromPhaseERPImage.R", dirname))
source(sprintf("%s/computeITCMaskedWithRayleighSignificance.R", dirname))
source(sprintf("%s/maskTimeFreqWithPValues.R", dirname))
source(sprintf("%s/maskTimeFreqWithCIs.R", dirname))
source(sprintf("%s/plotTimeFreqRes.R", dirname))
source(sprintf("%s/computeERSPandITCNoSignificance.R", dirname))
source(sprintf("%s/removeBaseline.R", dirname))
source(sprintf("%s/removeBaselines.R", dirname))
source(sprintf("%s/bootstrapERSP.R", dirname))
source(sprintf("%s/computeERSPandITCFromTimeFreqs.R", dirname))
source(sprintf("%s/computeERSPMaskedWithBootstrapSignificance.R", dirname))
source(sprintf("%s/computeERSPFromTimeFreqs.R", dirname))
source(sprintf("%s/computeERSPandITCMaskedWithBootstrapAndRayleighSignificance.R", dirname))
source(sprintf("%s/getPhasesAtTime.R", dirname))
source(sprintf("%s/binTrialsAmplitudesByPhase.R", dirname))
source(sprintf("%s/binAmplitudesByPhases.R", dirname))
source(sprintf("%s/performClippedMorletWTs.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/travelingWaves"
source(sprintf("%s/computeInstantaneousFrequencyForDatacube.R", dirname))
source(sprintf("%s/phaseGradientComplexMultiplication.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/signalProcessing"
source(sprintf("%s/lowpassKaiser.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/stats"
source(sprintf("%s/rayleighUniformityTest.R", dirname))
source(sprintf("%s/getBootstrapCIs.R", dirname))
source(sprintf("%s/getOutliersIndices.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/stats/bootstrap"
source(sprintf("%s/bootstrapColMeans.R", dirname))
source(sprintf("%s/bootstrapOneParamFunction.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/stats/permute"
source(sprintf("%s/permuteSkippedPearsonCorCoef.R", dirname))
source(sprintf("%s/permuteCorCoef.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/stats/circular"
source(sprintf("%s/computeCircularVariance.R", dirname))
source(sprintf("%s/computeMeanDirection.R", dirname))
source(sprintf("%s/computeMeanResultantLength.R", dirname))
rm(dirname)

dirname <- "/home/rapela/dev/research/programs/src/R/plots"
source(sprintf("%s/getEmptyPlot.R", dirname))
source(sprintf("%s/getPlotVectorField.R", dirname))
rm(dirname)

dirname <- "~/dev/research/programs/src/R/utils"
source(sprintf("%s/findPeaksOfTimeSeries.R", dirname))
# source(sprintf("%s/multiplot.R", dirname))
source(sprintf("%s/readVectorDoubleWithLengthHeader.R", dirname))
source(sprintf("%s/buildEmptyListOfVectors.R", dirname))
source(sprintf("%s/concatenateListsOfVectors.R", dirname))
source(sprintf("%s/last.R", dirname))
source(sprintf("%s/flipMatrixVertically.R", dirname))
source(sprintf("%s/rotateMatrixBy90DegreesClockwise.R", dirname))
source(sprintf("%s/meshgrid.R", dirname))
rm(dirname)

dirname <- "~/dev/research/eddyECoGSpeech/averageAnalysis"
source(sprintf("%s/getAbsoluteElectrodeNumber.R", dirname))
source(sprintf("%s/getNonOverlappingEpochs.R", dirname))
source(sprintf("%s/getInfoCVSsCVTransitions.R", dirname))
source(sprintf("%s/getInfoCVSsCVTransitions.R", dirname))
source(sprintf("%s/getInfoCVSsTerminations.R", dirname))
source(sprintf("%s/buildEpochs.R", dirname))
source(sprintf("%s/getNonOverlappingTimesIndices.R", dirname))
source(sprintf("%s/getStatsItem.R", dirname))
source(sprintf("%s/saveOneSetOfResults.R", dirname))
source(sprintf("%s/plotOneSetOfResults.R", dirname))
source(sprintf("%s/plotERP.R", dirname))
source(sprintf("%s/plotERPWithCI.R", dirname))
source(sprintf("%s/saveITCMaskedWithRayleighSignificance.R", dirname))
source(sprintf("%s/saveERSPMaskedWithBootstrapSignificance.R", dirname))
source(sprintf("%s/saveERSPandITCMaskedWithBootstrapAndRayleighSignificance.R", dirname))
source(sprintf("%s/savePhasesAtTime.R", dirname))
source(sprintf("%s/plotPhasesAtEntrainmentFreq.R", dirname))
source(sprintf("%s/getECoGSampleRate.R", dirname))
source(sprintf("%s/saveAmplitudesBinnedByPhase.R", dirname))
source(sprintf("%s/plotMediansAnd95CIsOfListOfVectors.R", dirname))
source(sprintf("%s/plotPhaseAmplitudeCoupling.R", dirname))
source(sprintf("%s/computeModulationIndex.R", dirname))
source(sprintf("%s/saveClippedMorletWTs.R", dirname))
source(sprintf("%s/getPhaseBinsCenters.R", dirname))
source(sprintf("%s/findLargeGapsInCVSProductions.R", dirname))
source(sprintf("%s/computeMIForMultipleFreqs.R", dirname))
source(sprintf("%s/plotMIForMultipleFreqs.R", dirname))
source(sprintf("%s/computePhaseDifferencesAtFreq.R", dirname))
source(sprintf("%s/computeArrayAvgPhases.R", dirname))
source(sprintf("%s/computeArrayPhases.R", dirname))
source(sprintf("%s/getGroupAndElecNumber.R", dirname))
# source(sprintf("%s/saveVoltageImages.R", dirname))
source(sprintf("%s/getElectrodeIndexInArrayGGPlot.R", dirname))
source(sprintf("%s/getPhasesArray.R", dirname))
source(sprintf("%s/getAmplitudesArray.R", dirname))
source(sprintf("%s/saveVoltageImagesWithSquare.R", dirname))
source(sprintf("%s/getVoltagesArray.R", dirname))
source(sprintf("%s/saveCosPhaseImages.R", dirname))
source(sprintf("%s/saveImagesFromArray.R", dirname))
source(sprintf("%s/saveCosPhaseImagesWithSquare.R", dirname))
source(sprintf("%s/getMeansCosPhaseInSquare.R", dirname))
source(sprintf("%s/saveAmplitudeImagesWithSquare.R", dirname))
# source(sprintf("%s/getMeansAmplitudeInSquare.R", dirname))
source(sprintf("%s/saveImagesWithSquareFromArray.R", dirname))
source(sprintf("%s/getClosestPeakInfoForCVSs.R", dirname))
# source(sprintf("%s/downsamplePhases.R", dirname))
source(sprintf("%s/getPlotMeansCosPhaseInSquare.R", dirname))
source(sprintf("%s/getPeakInfo.R", dirname))
source(sprintf("%s/getPeakTimesWithAndWithoutMatchingCVSs.R", dirname))
source(sprintf("%s/getPACAmplitudesForPhases.R", dirname))
source(sprintf("%s/saveAvgAmpImagesWithSquare.R", dirname))
source(sprintf("%s/getAvgAmpArray.R", dirname))
source(sprintf("%s/getButterworthOrderAndCriticalFreq.R", dirname))
source(sprintf("%s/getButterworthOrderAndNormalizedCriticalFreq.R", dirname))
source(sprintf("%s/saveBPVoltageImagesWithSquare.R", dirname))
source(sprintf("%s/getBPVoltagesArray.R", dirname))
source(sprintf("%s/getPlotTimeSeriesWithPeaksAndCVSs.R", dirname))
source(sprintf("%s/saveBPVoltageImagesGGPlot2.R", dirname))
source(sprintf("%s/saveAvgAmpImagesGGPlot2.R", dirname))
source(sprintf("%s/saveImagesFromDatacube.R", dirname))
source(sprintf("%s/runningFunction.R", dirname))
source(sprintf("%s/saveCosPhaseImagesGGPlot2.R", dirname))
source(sprintf("%s/saveVoltagePhaseAtCVSPresentationsImagesGGPlot2.R", dirname))
source(sprintf("%s/getVoltagePhasesAtCVSPresentationsArray.R", dirname))
source(sprintf("%s/buildHTDatacube.R", dirname))
source(sprintf("%s/saveGradientImages.R", dirname))
source(sprintf("%s/saveVectorFieldImages.R", dirname))
source(sprintf("%s/getGradientsToSave.R", dirname))
source(sprintf("%s/savePhaseImagesGGPlot2.R", dirname))
source(sprintf("%s/blurImageArray.R", dirname))
source(sprintf("%s/saveCVSBPVoltageImages.R", dirname))
source(sprintf("%s/getCVSBPVoltagesArray.R", dirname))
source(sprintf("%s/getCVSSamples.R", dirname))
source(sprintf("%s/saveCVSGradientImages.R", dirname))
source(sprintf("%s/getCVSGradientsToSave.R", dirname))
source(sprintf("%s/saveERPImagesGGPlot2.R", dirname))
source(sprintf("%s/getERPsArray.R", dirname))
source(sprintf("%s/getECoGData.R", dirname))
source(sprintf("%s/getLatenciesFromPrevPeak.R", dirname))
source(sprintf("%s/computePhaseCoherenceAtElectrode.R", dirname))
source(sprintf("%s/getNormalizedLatenciesFromLastValley.R", dirname))
source(sprintf("%s/getPeakIndices.R", dirname))
source(sprintf("%s/buildNLFLVDatacube.R", dirname))
source(sprintf("%s/performPermutationTestOfPhaseCoherenceAtElectrode.R", dirname))
source(sprintf("%s/computeCoherencesWithSignBtwClosestNeighbors.R", dirname))
source(sprintf("%s/computeCoherencesWithSignBtwClosestNeighborsAtDelay.R", dirname))
source(sprintf("%s/computeITCFromPhasesWithSign.R", dirname))
source(sprintf("%s/computePLIFromPhasesWithSign.R", dirname))
source(sprintf("%s/plotSignificantPhaseCoherencesBtwClosestNeighborsAtDelay.R", dirname))
source(sprintf("%s/saveAveragedPSD.R", dirname))
source(sprintf("%s/getInfoCVSsInitiations.R", dirname))
source(sprintf("%s/randomizeInfoInitAndTerm.R", dirname))
source(sprintf("%s/resampleStatNullLatenciesBtwCVSsAndCWEsPhase.R", dirname))
source(sprintf("%s/resamplePropCWEsInSilence.R", dirname))
source(sprintf("%s/getPropCWEsInSilenceOrCVS.R", dirname))
source(sprintf("%s/resampleNullPropCWEs.R", dirname))
# source(sprintf("%s/computePropSignTWsWithPosSpeedBtwBeforeAndAfterOverNSignTWsWithPosSpeed.R", dirname))
source(sprintf("%s/computePropCWEsOverlappingCVSs.R", dirname))
source(sprintf("%s/computePropSignTWsWithNegSpeedBtwAfterAndBeforeOverNSignTWsWithNegSpeed.R", dirname))
source(sprintf("%s/getCVSIndicesOverlappingCWE.R", dirname))
source(sprintf("%s/robustSkewness.R", dirname))
source(sprintf("%s/getPhaseDiffsWRTElec1AtTime.R", dirname))
source(sprintf("%s/getPlotPhaseDiffsVsDistances.R", dirname))
source(sprintf("%s/getHTsAndTimesForElectrodes.R", dirname))
source(sprintf("%s/getWaveEventsStats.R", dirname))
source(sprintf("%s/computePropEventsInSilence.R", dirname))
source(sprintf("%s/resampleNullPropEventsAlignedToCVSs.R", dirname))
source(sprintf("%s/getElectrodePhasesFromDatacube.R", dirname))
source(sprintf("%s/getNeighborsOfPixel.R", dirname))
source(sprintf("%s/getElectrodesPhasesFromDatacube.R", dirname))
source(sprintf("%s/unwrap1DPhases.R", dirname))
rm(dirname)

