
all: Joaco_3D_unwrapper Joaco_2D_unwrapper_for3DVolume Joaco_2D_unwrapper

Joaco_3D_unwrapper: Joaco_3D_unwrapper.cpp
	g++ -g Joaco_3D_unwrapper.cpp -o Joaco_3D_unwrapper

Joaco_2D_unwrapper_for3DVolume: Joaco_2D_unwrapper_for3DVolume.cpp
	g++ -g Joaco_2D_unwrapper_for3DVolume.cpp -o Joaco_2D_unwrapper_for3DVolume

Joaco_2D_unwrapper: Joaco_2D_unwrapper.cpp
	g++ -g Joaco_2D_unwrapper.cpp -o Joaco_2D_unwrapper

